# Generated by Django 3.2.16 on 2024-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20240228_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='diner',
            field=models.BooleanField(blank=True, default=True, verbose_name='ты покакал?'),
        ),
    ]
